name: Run Backend check - ensure project builds correctly

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    env:
      working-directory: './server'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Setup .Net Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install Dependencies
        run: dotnet restore
        working-directory: ${{ env.working-directory }}
      - name: Build
        run: dotnet build --no-restore
        working-directory: ${{ env.working-directory }}